Algoritmo "semnome"
// Descrição   : Aula 2 exe1 <  01.	Faça um algoritmo que receba 2 números
//inteiros e apresente a soma desses números.

// Autor(a)    : Bruno
// Data atual  : 22/06/2022
Var
    num1, num2,soma:inteiro


Inicio
      escreva("Digite um numero inteiro: ")
      leia(num1)
      escreva("Digite outro numero inteiro: ")
      leia(num2)
      soma<-num1+num2
      escreva(num1," + ",num2," = ",soma)

Fimalgoritmo