Algoritmo "Aula2_exe3"
// Descrição   : Faça um algoritmo que receba 2 números e
//apresente a multiplicação dos dois números

// Autor(a)    : Bruno ADS
// Data atual  : 22/06/2022
Var
   n1,n2,mult:real


Inicio
          escreva("Digite um numero: ")
          leia(n1)
          escreva("Digite outro numero: ")
          leia(n2)
          mult<-n1*n2
          escreval(n1," X",n2," =",mult)


Fimalgoritmo