Algoritmo "Aula2_exe2"

// Descrição   : . Faça um algoritmo que receba 2 números inteiros
//e mostre os dois números.

// Autor(a)    : Bruno ADS
// Data atual  : 22/06/2022
Var
      n1,n2:inteiro


Inicio
           escreva("Digite um numero inteiro: ")
           leia(n1)
           escreva("Digite outro numero inteiro: ")
           leia(n2)
           escreval("O 1° numero digitado foi: ",n1," e o 2° numero digitado foi: ",n2)


Fimalgoritmo